version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306" # Change the host port to 3307 or any other available port
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: strapi


  strapi:
    image: leticia888444/strapi_docker_final:1.0

    container_name: strapi
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
    depends_on:
      - mysql
